import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

function pathOf(path: string) {
  return resolve(process.cwd(), path);
}

function read(path: string) {
  return readFileSync(pathOf(path), "utf-8");
}

const packageJson = JSON.parse(read("package.json")) as {
  version: string;
  scripts: Record<string, string>;
  engines: Record<string, string>;
};
const packageLock = JSON.parse(read("package-lock.json")) as {
  version: string;
  lockfileVersion: number;
  packages: Record<string, { version?: string }>;
};
const tauriConfig = JSON.parse(read("src-tauri/tauri.conf.json")) as {
  version: string;
};
const cargoToml = read("src-tauri/Cargo.toml");
const cargoLock = read("src-tauri/Cargo.lock");
const readme = read("README.md");
const ciWorkflow = read(".github/workflows/ci.yml");
const releaseWorkflow = read(".github/workflows/release.yml");

describe("release readiness contract", () => {
  it("keeps JavaScript, Tauri and Rust versions aligned", () => {
    const cargoVersion = cargoToml.match(/^version = "([^"]+)"$/m)?.[1];

    expect(packageJson.version).toBe("1.0.0");
    expect(tauriConfig.version).toBe(packageJson.version);
    expect(cargoVersion).toBe(packageJson.version);
    expect(packageLock.version).toBe(packageJson.version);
    expect(packageLock.packages[""]?.version).toBe(packageJson.version);
  });

  it("provides one-command frontend and Rust verification", () => {
    expect(packageJson.scripts["verify:frontend"]).toContain("typecheck");
    expect(packageJson.scripts["verify:frontend"]).toContain("npm test");
    expect(packageJson.scripts["verify:frontend"]).toContain("npm run build");
    expect(packageJson.scripts["verify:rust"]).toContain("cargo fmt");
    expect(packageJson.scripts["verify:rust"]).toContain("cargo test --all-targets --locked");
    expect(packageJson.scripts.verify).toContain("verify:frontend");
    expect(packageJson.scripts.verify).toContain("verify:rust");
    expect(packageJson.engines.node).toBe(">=20.19.0");
    expect(packageJson.engines.npm).toBe(">=10.0.0");
  });

  it("commits npm and Cargo lockfiles and enforces them in CI", () => {
    expect(existsSync(pathOf("package-lock.json"))).toBe(true);
    expect(existsSync(pathOf("src-tauri/Cargo.lock"))).toBe(true);
    expect(packageLock.lockfileVersion).toBe(3);
    expect(cargoLock).toContain("# This file is automatically @generated by Cargo.");
    expect(cargoLock).toMatch(/^version = 3$/m);
    expect(ciWorkflow).toContain("actions/checkout@v7");
    expect(ciWorkflow).toContain("actions/setup-node@v6");
    expect(ciWorkflow).toContain("run: npm ci");
    expect(ciWorkflow).toContain("cargo test --all-targets --locked");
    expect(ciWorkflow).not.toContain("Generate deterministic lockfiles");
  });

  it("builds and verifies a real Linux Tauri installer in CI", () => {
    expect(ciWorkflow).toContain("Linux Tauri bundle smoke");
    expect(ciWorkflow).toContain("npm run tauri:build -- --bundles deb");
    expect(ciWorkflow).toContain("src-tauri/target/release/bundle/deb/*.deb");
    expect(ciWorkflow).toContain("Expected exactly one .deb bundle");
    expect(ciWorkflow).toContain("patchelf");
    expect(ciWorkflow).toContain("xdg-utils");
  });

  it("documents the real completed product and clean install", () => {
    expect(readme).toContain("41 ana geliştirme ve ürün sağlamlaştırma aşaması tamamlandı");
    expect(readme).toContain("npm ci");
    expect(readme).toContain("npm run verify");
    expect(readme).toContain("docs/RELEASE_CHECKLIST.md");
    expect(readme).not.toContain("Aşama 3 — Yerel Python çalışma motoru");
  });

  it("uses the current official Tauri draft release pipeline", () => {
    expect(releaseWorkflow).toContain("actions/checkout@v7");
    expect(releaseWorkflow).toContain("actions/setup-node@v6");
    expect(releaseWorkflow).toContain("tauri-apps/tauri-action@v1");
    expect(releaseWorkflow).toContain("npm ci");
    expect(releaseWorkflow).toContain("releaseDraft: true");
    expect(releaseWorkflow).toContain("prerelease: false");
    expect(releaseWorkflow).toContain("aarch64-apple-darwin");
    expect(releaseWorkflow).toContain("x86_64-apple-darwin");
    expect(releaseWorkflow).toContain("ubuntu-22.04");
    expect(releaseWorkflow).toContain("windows-latest");
    expect(releaseWorkflow).toContain("APPLE_SIGNING_IDENTITY");
    expect(releaseWorkflow).toContain("Build dry-run Tauri bundles");
  });

  it("rejects release tags that do not match all manifest versions", () => {
    expect(releaseWorkflow).toContain("Validate manifest versions and triggering tag");
    expect(releaseWorkflow).toContain("package_version");
    expect(releaseWorkflow).toContain("tauri_version");
    expect(releaseWorkflow).toContain("cargo_version");
    expect(releaseWorkflow).toContain('expected_tag="v${package_version}"');
    expect(releaseWorkflow).toContain("GITHUB_REF_TYPE");
    expect(releaseWorkflow).toContain("GITHUB_REF_NAME");
    expect(releaseWorkflow).toContain("tagName: ${{ github.ref_name }}");
    expect(releaseWorkflow).not.toContain("v__VERSION__");
  });
});
